### ISSUE TITLE
ci: dockerize setup

### ISSUE THREAD

**Issue by polarhive** [acmpesuecc/pasta#1]
Run pasta inside of a docker container, make sure the ports are exposed. Test and add documentation as well.

**Comment by JP-sDEV** [comment]
Hi @polarhive, can I work on this? 

> Sorry, this is out of scope for outsiders. For context: these repos are part of hacknight our college's hackathon. Feel free to work on it to post: 2024-10-20

**Comment by Delta18-Git** [comment]
Can I be assigned to this @polarhive ?

**Comment by polarhive** [comment]
sure go ahead

**Comment by Delta18-Git** [comment]
@polarhive Going for dinner, please extend the timeslot, and assign the issue. Thanks!

**Comment by Delta18-Git** [comment]
@polarhive Quick question, is the container supposed to be run on 8080 only or should it use another port if used in a non-dev environment?

**Comment by Delta18-Git** [comment]
See #8 @polarhive
