### ISSUE TITLE
chore: systemd unit to run pasta after reboots

### ISSUE THREAD

**Issue by polarhive** [acmpesuecc/pasta#2]
Write a `pasta.service` file to manage using systemd.

**Comment by unrelatedchase34** [comment]
assign this

**Comment by polarhive** [comment]
go ahead

**Comment by polarhive** [comment]
@unrelatedchase34 do you want to take this?

**Comment by Delta18-Git** [comment]
Hi, is this still free?

**Comment by polarhive** [comment]
Yes, go ahead! (no pun intended)

**Comment by polarhive** [comment]
!assign @Delta18-Git

**Comment by Delta18-Git** [comment]
Quick question, what would the path to pasta be in this case? Would it be stored in /usr/bin?

**Comment by Delta18-Git** [comment]
Or would it be in cwd/pasta?

**Comment by polarhive** [comment]
> Quick question, what would the path to pasta be in this case? Would it be stored in /usr/bin?

/usr/bin

or /home/username/pasta

**Comment by Delta18-Git** [comment]
I did /usr/bin here, I can make a second service for username.

**Comment by Delta18-Git** [comment]
Made a PR #10

**Comment by polarhive** [comment]
!deassign
