### ISSUE TITLE
feat: auth

### ISSUE THREAD

**Issue by polarhive** [acmpesuecc/pasta#3]
- [x] Setup basic passphrase based authentication when sending pastes over HTTPS
- [x] Consider using HTTP headers for passing the passphrase, `X-Auth-Passphrase`
- [x] Use environment variables, do not hard-encode the password within the Go binary
- [ ] Setup a rate-limit to prevent brute-force attacks like how [fail2ban](https://github.com/fail2ban/fail2ban) does. (~200 bounty points weight)

**Comment by ManishMDharani** [comment]
can i get assigned?

**Comment by polarhive** [comment]
!assign @ManishMDharani

**Comment by polarhive** [comment]
!assign @ManishMDharani

**Comment by polarhive** [comment]
!deassign @ManishMDharani

**Comment by ManishMDharani** [comment]
can i please get this assigned?

**Comment by polarhive** [comment]
!assign @ManishMDharani

**Comment by polarhive** [comment]
!deassign

**Comment by polarhive** [comment]
@ManishMDharani do you want to take this?

**Comment by Delta18-Git** [comment]
I kinda did this. Can I make a PR‌ real quick?

**Comment by Delta18-Git** [comment]
problem I'm facing is that the rate limit isn't expiring...

**Comment by Delta18-Git** [comment]
I was mistaken it works

**Comment by Delta18-Git** [comment]
#11 is the PR

**Comment by polarhive** [comment]
What I'm looking for is a mechanism that tracks failed `$PASSPHRASE` header attempts by IP. For instance, after each failed passphrase, the cooldown for that IP could be increased by 5 minutes.

```go

 	// Check for passphrase in headers
	if r.Header.Get("X-Auth-Passphrase") != passphrase {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
```

While your rate-limiting effectively prevents spammy behavior and limits excessive requests from the **same** IP, it doesn’t currently provide protection against brute force password attacks since failed passphrase attempts aren’t tracked separately.

I can `!extend` your time if you'd like to work on it for the rest of the bounty points.

**Comment by Delta18-Git** [comment]
Hi sorry, I was on my way home and didn't see the update, Thanks for the advice, I'll work on this when I have more time next week for fun. Thanks!
