### ISSUE TITLE
bug: check for dups

### ISSUE THREAD

**Issue by polarhive** [acmpesuecc/pasta#5]
Check for duplicate entries and re-use if they match hashes. This should be an easy 20 point issue. Try optimizing when you have a large number text files. Think of edge-cases (try not to hash all previous `data/` entries on every run :thinking: )

**Comment by sakshipai213** [comment]
please assign this issue to me

**Comment by unrelatedchase34** [comment]
assign this!

**Comment by polarhive** [comment]
done!
